config/routes.rb
Rails.application.routes.draw do
  resources :devices

end

app/models/device.rb
class Device < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  # GET /devices
  # GET /devices.json
  def index
    @devices = Device.all
  end

  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = Device.new(device_params)

    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, notice: 'Device was successfully created.' }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, notice: 'Device was successfully updated.' }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def device_params
      params.require(:device).permit(:responsable, :departamento, :marca, :modelo, :serie, :factura, :proveedor, :mac_address, :procesador, :memoria, :DD, :SistemaOperativo, :factura_SO, :Licencia_SO, :Office, :Licencia_Office)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :responsable %><br>
    <%= f.text_field :responsable %>
  </div>
  <div class="field">
    <%= f.label :departamento %><br>
    <%= f.text_field :departamento %>
  </div>
  <div class="field">
    <%= f.label :marca %><br>
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :modelo %><br>
    <%= f.text_field :modelo %>
  </div>
  <div class="field">
    <%= f.label :serie %><br>
    <%= f.text_field :serie %>
  </div>
  <div class="field">
    <%= f.label :factura %><br>
    <%= f.text_field :factura %>
  </div>
  <div class="field">
    <%= f.label :proveedor %><br>
    <%= f.text_field :proveedor %>
  </div>
  <div class="field">
    <%= f.label :mac_address %><br>
    <%= f.text_field :mac_address %>
  </div>
  <div class="field">
    <%= f.label :procesador %><br>
    <%= f.text_field :procesador %>
  </div>
  <div class="field">
    <%= f.label :memoria %><br>
    <%= f.text_field :memoria %>
  </div>
  <div class="field">
    <%= f.label :DD %><br>
    <%= f.text_field :DD %>
  </div>
  <div class="field">
    <%= f.label :SistemaOperativo %><br>
    <%= f.text_field :SistemaOperativo %>
  </div>
  <div class="field">
    <%= f.label :factura_SO %><br>
    <%= f.text_field :factura_SO %>
  </div>
  <div class="field">
    <%= f.label :Licencia_SO %><br>
    <%= f.text_field :Licencia_SO %>
  </div>
  <div class="field">
    <%= f.label :Office %><br>
    <%= f.text_field :Office %>
  </div>
  <div class="field">
    <%= f.label :Licencia_Office %><br>
    <%= f.text_field :Licencia_Office %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form' %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Devices</h1>

<table>
  <thead>
    <tr>
      <th>Responsable</th>
      <th>Departamento</th>
      <th>Marca</th>
      <th>Modelo</th>
      <th>Serie</th>
      <th>Factura</th>
      <th>Proveedor</th>
      <th>Mac address</th>
      <th>Procesador</th>
      <th>Memoria</th>
      <th>Dd</th>
      <th>Sistemaoperativo</th>
      <th>Factura so</th>
      <th>Licencia so</th>
      <th>Office</th>
      <th>Licencia office</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.responsable %></td>
        <td><%= device.departamento %></td>
        <td><%= device.marca %></td>
        <td><%= device.modelo %></td>
        <td><%= device.serie %></td>
        <td><%= device.factura %></td>
        <td><%= device.proveedor %></td>
        <td><%= device.mac_address %></td>
        <td><%= device.procesador %></td>
        <td><%= device.memoria %></td>
        <td><%= device.DD %></td>
        <td><%= device.SistemaOperativo %></td>
        <td><%= device.factura_SO %></td>
        <td><%= device.Licencia_SO %></td>
        <td><%= device.Office %></td>
        <td><%= device.Licencia_Office %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Responsable:</strong>
  <%= @device.responsable %>
</p>

<p>
  <strong>Departamento:</strong>
  <%= @device.departamento %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @device.marca %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @device.modelo %>
</p>

<p>
  <strong>Serie:</strong>
  <%= @device.serie %>
</p>

<p>
  <strong>Factura:</strong>
  <%= @device.factura %>
</p>

<p>
  <strong>Proveedor:</strong>
  <%= @device.proveedor %>
</p>

<p>
  <strong>Mac address:</strong>
  <%= @device.mac_address %>
</p>

<p>
  <strong>Procesador:</strong>
  <%= @device.procesador %>
</p>

<p>
  <strong>Memoria:</strong>
  <%= @device.memoria %>
</p>

<p>
  <strong>Dd:</strong>
  <%= @device.DD %>
</p>

<p>
  <strong>Sistemaoperativo:</strong>
  <%= @device.SistemaOperativo %>
</p>

<p>
  <strong>Factura so:</strong>
  <%= @device.factura_SO %>
</p>

<p>
  <strong>Licencia so:</strong>
  <%= @device.Licencia_SO %>
</p>

<p>
  <strong>Office:</strong>
  <%= @device.Office %>
</p>

<p>
  <strong>Licencia office:</strong>
  <%= @device.Licencia_Office %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inventario</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>